const API=location.protocol==='file:'?'http://127.0.0.1:8000':location.origin;
const $=s=>document.querySelector(s); const messages=$('#messages');
let conversationId=null, mediaLoaded=false, busy=false, voiceEnabled=false, started=Date.now();
const state={avatar:'idle',theme:localStorage.getItem('aig-theme')||'dark',sessions:+localStorage.getItem('aig-sessions')||0};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function setAvatar(s){state.avatar=s;$('#avatarState').textContent=s.toUpperCase()+' · DEMO ACTIVE';document.body.dataset.avatar=s;$('#typingState').textContent=s==='thinking'?'ARCANA está analizando…':s==='speaking'?'ARCANA está respondiendo…':'ARCANA preparada'}
function updateSession(){ $('#sessionLabel').textContent=conversationId?`Sesión ${conversationId.slice(0,8)}…`:'Sin sesión activa'; $('#metricConversations').textContent=state.sessions; }
function addMessage(role,text,opts={}){ $('#hero')?.remove(); const el=document.createElement('article'); el.className=`message ${role}`; el.innerHTML=`<div class="msg-avatar">${role==='arcana'?'A':'T'}</div><div class="msg-content"><div class="msg-head"><b>${role==='arcana'?'ARCANA':'TÚ'}</b><span>${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></div><div class="msg-body">${opts.html?text:esc(text).replace(/\n/g,'<br>')}</div>${role==='arcana'?'<div class="msg-actions"><button data-copy>Copiar</button><button data-voice>Escuchar</button></div>':''}</div>`; messages.appendChild(el); messages.scrollTop=messages.scrollHeight; el.querySelector('[data-copy]')?.addEventListener('click',()=>navigator.clipboard.writeText(text).then(()=>toast('Respuesta copiada'))); el.querySelector('[data-voice]')?.addEventListener('click',()=>speak(text)); return el; }
function typing(){const e=document.createElement('article');e.className='message arcana typing';e.innerHTML='<div class="msg-avatar">A</div><div class="msg-content"><div class="msg-head"><b>ARCANA</b><span>thinking</span></div><div class="dots"><i></i><i></i><i></i></div></div>';messages.appendChild(e);messages.scrollTop=messages.scrollHeight;return e}
async function api(path,options={}){const headers={...(options.headers||{})};if(options.body && !(options.body instanceof FormData)) headers['Content-Type']='application/json'; const start=performance.now(); const r=await fetch(API+path,{...options,headers});$('#latency').textContent=Math.round(performance.now()-start)+'ms';if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail||'Error'));}return r.json()}
async function check(){try{const d=await api('/ready');const c=$('#connection');c.className='connection '+(d.ready?'ok':'warn');c.innerHTML=`<i></i><span>${d.ready?'Sistema listo':'Modelo pendiente'}</span>`;$('#modelState').textContent=d.chat_model||'LOCAL AI'}catch{const c=$('#connection');c.className='connection bad';c.innerHTML='<i></i><span>Backend offline</span>'}}
async function send(text){text=text.trim();if(!text||busy)return;busy=true;addMessage('user',text);setAvatar('thinking');const t=typing();try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({message:text,conversation_id:conversationId,persona_id:'arcana'})});conversationId=d.conversation_id;if(!localStorage.getItem('aig-session-'+conversationId)){state.sessions++;localStorage.setItem('aig-session-'+conversationId,'1');localStorage.setItem('aig-sessions',state.sessions)}updateSession();t.remove();setAvatar('speaking');addMessage('arcana',d.response);if(voiceEnabled)speak(d.response)}catch(e){t.remove();setAvatar('error');addMessage('arcana','El núcleo local no ha podido responder. '+e.message)}finally{busy=false;setTimeout(()=>setAvatar('idle'),500)}}
async function draw(){if(busy)return;busy=true;setAvatar('thinking');const t=typing();try{const d=await api('/api/tarot/draw',{method:'POST',body:JSON.stringify({conversation_id:conversationId,persona_id:'arcana'})});conversationId=d.conversation_id;updateSession();t.remove();const box=$('#cards');box.innerHTML=d.cards.map((c,i)=>`<article class="card"><div class="card-num">0${i+1}</div><small>${esc(c.position)}</small><h3>${esc(c.name)}</h3><p>${esc(c.meaning)}</p></article>`).join('');box.classList.remove('hidden');setAvatar('speaking');addMessage('arcana',d.interpretation);if(voiceEnabled)speak(d.interpretation)}catch(e){t.remove();addMessage('arcana','La tirada no pudo completarse. '+e.message)}finally{busy=false;setTimeout(()=>setAvatar('idle'),500)}}
async function loadMedia(){const panel=$('#mediaPanel');panel.classList.remove('hidden');if(mediaLoaded)return;try{const d=await api('/api/media');mediaLoaded=true;$('#mediaGrid').innerHTML=d.items.length?d.items.map(x=>x.type==='video'?`<figure><video controls preload="metadata" src="${x.url}"></video><figcaption>${esc(x.name)}</figcaption></figure>`:`<figure><img src="${x.url}" alt="${esc(x.name)}"><figcaption>${esc(x.name)}</figcaption></figure>`).join(''):'<p>No hay assets todavía.</p>'}catch(e){$('#mediaGrid').textContent=e.message}}
function speak(text){if(!('speechSynthesis'in window)){toast('Voz no disponible en este navegador');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-ES';u.rate=.98;u.onstart=()=>setAvatar('speaking');u.onend=()=>setAvatar('idle');speechSynthesis.speak(u)}
function exportChat(){const content=[...document.querySelectorAll('.message')].map(m=>m.innerText).join('\n\n');const blob=new Blob([`AIGORITMO · ARCANA\nExported: ${new Date().toISOString()}\n\n${content}`],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='arcana-conversation.txt';a.click();URL.revokeObjectURL(a.href);toast('Conversación exportada')}
async function analyzeVision(){const f=$('#visionFile').files[0],q=$('#visionQuestion').value.trim();if(!f||!q){toast('Selecciona una imagen y escribe una pregunta');return}const fd=new FormData();fd.append('file',f);fd.append('question',q);fd.append('persona_id','arcana');if(conversationId)fd.append('conversation_id',conversationId);setAvatar('thinking');try{const r=await fetch(API+'/api/vision',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw Error(d.detail||'Error de visión');conversationId=d.conversation_id;updateSession();addMessage('user','[VISION] '+q);addMessage('arcana',d.response);$('#visionPanel').classList.add('hidden')}catch(e){toast(e.message)}finally{setAvatar('idle')}}
$('#chatForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#message'),text=input.value;input.value='';$('#charCount').textContent='0 / 6000';await send(text)});
$('#message').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,180)+'px';$('#charCount').textContent=e.target.value.length+' / 6000'});
$('#message').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatForm').requestSubmit()}});
$('#drawBtn').onclick=draw;$('#heroDraw').onclick=draw;$('#startDemo').onclick=()=>$('#message').focus();$('#mediaToggle').onclick=loadMedia;$('#closeMedia').onclick=()=>$('#mediaPanel').classList.add('hidden');$('#visionToggle').onclick=()=>$('#visionPanel').classList.toggle('hidden');$('#closeVision').onclick=()=>$('#visionPanel').classList.add('hidden');$('#analyzeVision').onclick=analyzeVision;
$('#newConversation').onclick=()=>{conversationId=null;messages.innerHTML='';$('#cards').classList.add('hidden');updateSession();setAvatar('idle');addMessage('arcana','Nueva conversación iniciada. Soy ARCANA. Mi contexto para esta sesión comienza ahora.')};
$('#copyId').onclick=async()=>{if(!conversationId)return toast('Aún no existe una sesión');await navigator.clipboard.writeText(conversationId);toast('Session ID copiado')};$('#exportChat').onclick=exportChat;
$('#voiceBtn').onclick=()=>{voiceEnabled=!voiceEnabled;$('#voiceBtn').classList.toggle('muted',!voiceEnabled);$('#voiceBtn').textContent=voiceEnabled?'🔊 Voz activa':'🔊 Voz'};
$('#themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;localStorage.setItem('aig-theme',state.theme)};
$('#toggleDemo').onclick=()=>$('#demoOverlay').classList.remove('hidden');$('#closeDemo').onclick=()=>$('#demoOverlay').classList.add('hidden');document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>send(b.dataset.prompt));
document.documentElement.dataset.theme=state.theme;updateSession();setAvatar('idle');addMessage('arcana','Soy ARCANA. Esta es una demostración de AIGORITMO: una plataforma para avatares especializados con identidad, memoria contextual, visión y capacidades multimodales.');check();setInterval(check,30000);
